//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSUCorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int FriendID { get; set; }
        public string FriendUserName1 { get; set; }
        public string FriendUserName2 { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
