//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSUCorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public string SentBy { get; set; }
        public string SentTo { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string MessageType { get; set; }
        public string MessageStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
    }
}
